#-------------------------------
# General Site Settings

title: Kross - Jekyll Portfolio Template
logo: logo.png
email: abhiajoy23@gmail.com

menu:
- {name: About, link: '/about/'}
- {name: Blog, link: '/blog/'}
- {name: Portfolio, link: '/portfolio/'}
- {name: Contact, link: '/contact/'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Abhishek <br> Software Engineer

social:
- {icon: "ti-facebook", link: "https://www.facebook.com/Abhishek.Ajoy.Menon"}
- {icon: "ti-instagram", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  I am  a Btech graduate from Rajagiri School of Engineering & Technology.
blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"




#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Angular, color: '#fdb157', value: '70%'}
- {name: Python, color: '#9473e6', value: '80%'}
- {name: C/C++, color: '#bdecf6', value: '80%'}
- {name: Java, color: '#ffbcaa', value: '60%'}
- {name: Machine Learning, color: '#febcaa', value: '60%'}



#-------------------------------
# Education Section

education-title: Education
education:
- {name: BTech, date: '2017-2021', organization: 'Rajagiri School of Engineering & Technology'}
- {name: Grade 12, date: '2017', organization: 'Sunrise English Private School'}
- {name: Grade 10, date: '2015', organization: 'Sunrise English Private School'}




#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: abhiajoy23@email.com
